### ISSUE TITLE
a bug about CUDA

### ISSUE THREAD

**Issue by ansixwu** [garyzhao/SemGCN#10]
File "/home/dm/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/functional.py", line 941, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: invalid argument

HI
is there someone happen for this problem,my environment is ubuntu16.04, pytorch==1.1.0,python=2.7

**Comment by garyzhao** [comment]
Hi @ansixwu ,

Could you please provide more information about the bug?

Best,
Long

**Comment by ansixwu** [comment]
thanks @garyzhao ,
I haved solved the bug . because of my cuda version and pytorch version isn't match.
