### ISSUE TITLE
Configuration 2?

### ISSUE THREAD

**Issue by ghumpire** [garyzhao/SemGCN#24]
Hi, nice paper! In the Readme you indicate this repo runs the Configuration 1 of the paper (2D joints of the human pose as inputs). Is there a way to train the Configuration 2 (2D images as input)?

**Comment by garyzhao** [comment]
Hi @ghumpire ,

Thanks for your interest in our work!

Currently, we do not have the plan to release Config 2, since the setting is quite different. We may release another repo for it in the future.

Best,
Long
