### ISSUE TITLE
fine-tuned dataset

### ISSUE THREAD

**Issue by wumb** [garyzhao/SemGCN#25]
Thanks for your sharing.
I applied for the access to the fine-tuned dataset, but there was no response. Could you plesase send it to my e-mail(wumengbin@hnu.edu.cn) so that I can reproduce it as soon as possible.

**Comment by garyzhao** [comment]
Hi @wumb ,

Please download the data here: https://drive.google.com/drive/folders/1c7Iz6Tt7qbaw0c1snKgcGOD-JGSzuZ4X

Best,
Long

**Comment by wumb** [comment]
Got it!
Thanks for your reply!!
