### ISSUE TITLE
confused about `View-disentangled Human Pose Representation ` on arxiv

### ISSUE THREAD

**Issue by Wjk666** [garyzhao/SemGCN#38]
Hi, Long~
Recently, I am very interested in your paper 'Learning View-disentangled Human Pose Representation by Contrastive cross-view Mutual Information Maximization' which is posted on the arxiv. Among them, I am very curious about the method you use to minimize mutual information to achieve Disentangle. I study the direction of graph data. Due to the needs of the project, I have a strong demand for disentangling to achieve mutual information minimization. Then, I am also interested in the approximation method of the upper bound of mutual information based on 2020ICML-club: A contrastive log-ratio upper bound of mutual information. Unfortunately, I cannot converge well with it in my own model, and even negative values often occur. Therefore, I am sorry to bother you, and I would like to ask you some question:
1: Do you have any adjustment or improvement on the source code processing method that you and 2020ICML hang out? Or is it convenient for you to talk about your experience or views on the convergence of mutual information to minimize the loss?
2: Does the idea of mutual information minimization realize decoupling contribute significantly to the effectiveness of your model? Maybe due to my lack of basic knowledge at present, I only have a general understanding of 2020ICML about mutual information minimization, and I still have some confusion about how to apply it.
Please forgive me if I disturb you!
Best wishes
> reference:
> CLUB: A contrastive log-ratio upper bound of mutual information. Pengyu Cheng. In ICML, 2020

**Comment by garyzhao** [comment]
Hi @Wjk666 ,

I just replied to your email. Please check it and feel free to let me know if you have any other questions.

Best,
Long

**Comment by garyzhao** [comment]
Closed this issue since it is not related to SemGCN.
