### ISSUE TITLE
2D pose estimation network

### ISSUE THREAD

**Issue by zhangyahu1** [garyzhao/SemGCN#6]
Hi,

Good work!
May I know the details of 2D pose estimation network in your paper? similar to 'Simple baselines for Human Pose Estimation' or modified Resnet50?

**Comment by garyzhao** [comment]
Hi, thanks for your interest in our work.

We use the 2D pose network presented in "Integral Human Pose Regression, ECCV 2018" (Resnet50 with deconv head). I think it is quite similar to the one in "Simple baselines for Human Pose Estimation".

Best,
Long

**Comment by zhangyahu1** [comment]
Thanks for your quick response!
