### ISSUE TITLE
Bone constraints in loss

### ISSUE THREAD

**Issue by ShallowWill** [garyzhao/SemGCN#9]
Hi, Gary, Thanks for the code. Did you implement combination of joint and bone constraints as loss in the code as described in your paper?

**Comment by garyzhao** [comment]
Hi @ShallowWill 

Thanks for your interest in our work. 

Unfortunately, bone loss is not implemented in this repo. It is only used in Config 2 of the paper, and it does improve the performance in  Config 1 (this repo). So we do not provide it here. But given the graph representation of the skeleton in this repo, it should be very easy to implement. Thanks.

Best,
Long
